name: build-and-publish-using-jupyter-to-pages

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
permissions:
  contents: write

jobs:
  prep-and-run-jupyter-to-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish Jupyter Notebooks as Github pages
        uses: dada-public/jupyter-to-pages@v1
        with:
          show-cells: true
          source: docs
