name: Build and publish analemma package documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish-sundial-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
  
      - name: Install project dependencies
        run: pip install -r requirements_dev.txt && pip install -e .
        shell: bash
  
      - name: Wrap LaTeX output
        run: |
          python scripts/dollar_dollar.py docs/sundial.ipynb docs/sundial.ipynb
        shell: bash
  
      - name: Jupyter to Markdown Conversion
        run: |
          find docs -type 'f' -name '*.ipynb' -not -name "*-checkpoint.ipynb" | xargs jupyter nbconvert --to Markdown
        shell: bash
  
      - name: Trigger publishing
        run: |
          mkdocs gh-deploy --clean --force
        shell: bash
