name: Build and publish sundial notebooks
author: Russell Goyder
description: Workflow to publish sundial workbooks with custom step to hack around LaTeX issues

inputs:
  source:
    description: Path to the folder that contains the Notebooks
    default: docs

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

permissions:
  contents: write

jobs:
  publish-sundial-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
  
      - name: Install project dependencies
        run: pip install -r ${{ inputs.dependencies }}
        shell: bash
  
      - name: Wrap LaTeX output
        run: |
          python dollar_dollar.py docs/sundial.ipynb docs/index.ipynb
          rm docs/sundial.ipynb
        shell: bash
  
      - name: Jupyter to Markdown Conversion
        run: |
          find ${{ inputs.source }} -type 'f' -name '*.ipynb' -not -name "*-checkpoint.ipynb" | xargs jupyter nbconvert --to Markdown
          find ${{ inputs.source }} -type 'f' -name "*.ipynb" -delete
        shell: bash
  
      - name: Trigger publishing
        run: |
          mkdocs gh-deploy --clean --force
        shell: bash
